
from os import system, name
from time import sleep


def clear():
    if name == 'nt':
        _ = system('cls')

    else:
        _ = system('clear')


def loading():
    print('Car game...')
    sleep(1)
    print('ver: 1.5.0')
    sleep(1)
    print('loading:')
    sleep(0.1)
    clear()
    print('loading:▮')
    sleep(0.3)
    clear()
    print('loading:▮▮')
    sleep(0.5)
    clear()
    print('loading:▮▮▮')
    sleep(2)
    clear()
    print('loading:▮▮▮▮')
    sleep(0.87)
    clear()
    print('loading:▮▮▮▮▮')
    sleep(0.4)
    clear()
    print('loading:▮▮▮▮▮▮')
    sleep(0.1)
    clear()
    print('loading:▮▮▮▮▮▮▮')
    sleep(0.1)
    clear()
    print('loading:▮▮▮▮▮▮▮▮▮')
    sleep(0.1)
    clear()
    print('loading:▮▮▮▮▮▮▮▮▮▮')
    sleep(0.2)
    clear()
    print('loading:▮▮▮▮▮▮▮▮▮▮▮')
    sleep(0.1)
    clear()
    print('loading:▮▮▮▮▮▮▮▮▮▮▮▮')
    sleep(8)
    clear()
    print('loading:▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮')
    sleep(0.16)
    clear()
    print('loading:▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮')
    sleep(1)
    clear()
    print('loading:▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮')
    sleep(0.1)
    clear()
    print('loading:▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮')
    sleep(1)
    clear()
    print('loading: done!')
    print('game start in 3')
    sleep(1)
    clear()
    print('loading: done!')
    print('game start in 2')
    sleep(1)
    clear()
    print('loading: done!')
    print('game start in 1')
    sleep(1)
    clear()
    print("game start")


